# Generated by Django 4.2 on 2023-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_open',
            new_name='active',
        ),
    ]
